-- ========================================================
-- ESQUEMA DE BASE DE DATOS PARA EDUNEXUS (SUPABASE)
-- Copia y ejecuta este script en el SQL Editor de tu Dashboard de Supabase
-- ========================================================

-- 1. TABLA DE PERFILES DE USUARIO
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  role_type TEXT NOT NULL DEFAULT 'student', -- 'student' o 'teacher'
  role_title TEXT,
  level_or_department TEXT,
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS en profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Los usuarios pueden ver todos los perfiles" 
  ON public.profiles FOR SELECT USING (true);

CREATE POLICY "Los usuarios pueden actualizar su propio perfil" 
  ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 2. TABLA DE GUÍAS DE ESTUDIO
CREATE TABLE IF NOT EXISTS public.guias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  grade TEXT NOT NULL,
  author TEXT NOT NULL,
  author_id UUID REFERENCES auth.users(id),
  materia_id TEXT,
  description TEXT,
  content TEXT,
  download_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.guias ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir lectura publica de guias" ON public.guias FOR SELECT USING (true);
CREATE POLICY "Permitir insercion a docentes" ON public.guias FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir edicion a creadores/docentes" ON public.guias FOR UPDATE USING (true);
CREATE POLICY "Permitir eliminacion a creadores/docentes" ON public.guias FOR DELETE USING (true);

-- 3. TABLA DE TALLERES INTERACTIVOS
CREATE TABLE IF NOT EXISTS public.talleres (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  difficulty TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Disponible',
  assigned_to TEXT,
  due_date TEXT,
  description TEXT,
  author TEXT,
  materia_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.talleres ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir lectura publica de talleres" ON public.talleres FOR SELECT USING (true);
CREATE POLICY "Permitir insercion a docentes" ON public.talleres FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir edicion a docentes" ON public.talleres FOR UPDATE USING (true);
CREATE POLICY "Permitir eliminacion a docentes" ON public.talleres FOR DELETE USING (true);

-- 4. TABLA DE CLASES EN VIVO
CREATE TABLE IF NOT EXISTS public.clases_live (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  instructor TEXT NOT NULL,
  date TEXT NOT NULL,
  time TEXT NOT NULL,
  materia_id TEXT,
  status TEXT NOT NULL DEFAULT 'Programada', -- 'En Vivo', 'Programada', 'Finalizada'
  viewers INT DEFAULT 0,
  link TEXT,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.clases_live ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir lectura publica de clases" ON public.clases_live FOR SELECT USING (true);
CREATE POLICY "Permitir insercion a docentes" ON public.clases_live FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir edicion a docentes" ON public.clases_live FOR UPDATE USING (true);
CREATE POLICY "Permitir eliminacion a docentes" ON public.clases_live FOR DELETE USING (true);

-- 5. TABLA DE NOTIFICACIONES
CREATE TABLE IF NOT EXISTS public.notificaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  for_role TEXT NOT NULL, -- 'student' o 'teacher'
  title TEXT NOT NULL,
  text TEXT NOT NULL,
  time TEXT NOT NULL,
  unread BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.notificaciones ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir lectura de notificaciones" ON public.notificaciones FOR SELECT USING (true);
CREATE POLICY "Permitir actualizacion de notificaciones" ON public.notificaciones FOR UPDATE USING (true);

-- ========================================================
-- DATOS SEMILLA (SEEDS OPCIONALES)
-- ========================================================

INSERT INTO public.guias (title, category, grade, author, description, content) VALUES
('Guía de Cálculo Diferencial e Integral', 'Matemáticas', '11° Grado', 'Prof. Carlos Gómez', 'Conceptos fundamentales de límites, derivadas e integrales.', 'Contenido explicativo de cálculo...'),
('Fundamentos de Robótica y Algoritmos', 'Tecnología', '10° - 11° Grado', 'Prof. Carlos Gómez', 'Introducción a microcontroladores y lógica secuencial.', 'Contenido explicativo de robótica...'),
('Química Orgánica y Enlaces Moleculares', 'Ciencias', '11° Grado', 'Dra. María Curiel', 'Estructura de hidrocarburos y grupos funcionales.', 'Contenido explicativo de química...');

INSERT INTO public.talleres (title, category, difficulty, status, assigned_to, due_date, description, author) VALUES
('Simulación de Algoritmos en Python', 'Programación', 'Intermedio', 'Disponible', 'Todos los Estudiantes', '2026-09-20', 'Desarrollo de scripts interactivos.', 'Prof. Carlos Gómez'),
('Resolución de Problemas Vectoriales', 'Física', 'Avanzado', 'Asignado', 'María López', '2026-09-15', 'Taller práctico sobre vectores tridimensionales.', 'Prof. Carlos Gómez');

INSERT INTO public.clases_live (title, instructor, date, time, status, viewers, description) VALUES
('Resolución de Problemas de Cálculo', 'Prof. Carlos Gómez', 'Hoy', '16:00 PM', 'Programada', 42, 'Sesión en vivo de repaso para el examen trimestral.');

INSERT INTO public.notificaciones (for_role, title, text, time, unread) VALUES
('student', 'Nueva clase en vivo', 'Matemáticas Avanzadas inicia en 15 minutos.', 'Hace 10 min', true),
('teacher', 'Entrega de Taller', 'La estudiante María López entregó el Taller de Robótica.', 'Hace 5 min', true);
